language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: sqrt@octoblu.com
  api_key:
    secure: hKy1HR49RZNoFHd7edfWfnf77kZyNU+mMDVeRGabYQaSJY/hudQ/CD4xa409rijqzPeUpVOz+ESorIGZp0e0O/7j3ic48bhBnuZdx75qmsMgRQbW4sLf9rUwOIC6sdDStbpdJ2oi1SjnkG6FzuQQ9JWMl+NCtN8ATsDVPfEPwCkHTQ8SrYfp7O8t94TZnTWVcAEi45A+75ywiuMiTOgBxOoIc0aSRF2b1gmy+9d97CSxkt7vRZcgMwu6v1BqcCktctL88T0K71QVXEtMTAHdszpS/I0IXgRbACudyzaTjAalfrNVmwCIahqH7sJ7GdYo5sYtcCe3sJM+Fo2N88PdvAiSbi7FIQDjG+ixBNDVJALCgiN2DHLa22EIa8ZSzrr7MjlPgX0+MKbfXO4LEbKLXzq07ivRiLRoRBDCi0RIKHod01nMeUGhbSOvJeRm3yf8m5O7KN2v+vrXymwrbyugO9tRJYsDWm6c2P6qdF2Bs83F55V1VkferNHBK0Hv90aU9/WwffIOexGFen8csqcxPuOMXP07Qu1MsdNu7LKRICF+68e8/o4oXOPIWcrft3HG70dIkaloTpkQzKRbrn7rFdCYtmmZdGRdgtqXh355ZzQGiSQNBibevONINcHmNkgZUQLUJganwWA9MFLGg21bR052m1LBQ3Am2VMHTSJjyKg=
  on:
    tags: true
    all_branches: true
